const express = require('express')
const authController = require('../controller/auth')
const authLogin = require('../controller/login')
const authTeacherReg = require('../controller/teacherReg')
const authForget = require('../controller/forget')
const authSchedule = require('../controller/schedule')
const authAdmin = require('../controller/admin')
const authTeacherEdit = require('../controller/teacherEdit')
const authArchive = require('../controller/archive')
const authStudentEdit = require('../controller/studentEdit')
const authArchiveStudent = require('../controller/archive_student')
const authAdminEdit = require('../controller/adminEdit')
const authAdminArchive = require('../controller/archive_admin')
const authScheduleEdit = require('../controller/editSchedule')
const authScheduleArchive = require('../controller/archive_schedule')
const authUnAdminArchive = require('../unArchive/admin')
const authUnScheduleArchive = require('../unArchive/schedule')
const authUnArchiveStudent = require('../unArchive/student')
const authUnArchive = require('../unArchive/teacher')
const router = express.Router()

router.post('/register', authController.register)
router.post('/login',  authLogin.login)
router.post('/Studentlogin',  authLogin.Studentlogin)
router.post('/Teacherlogin',  authLogin.Teacherlogin)
router.post('/teacherRegister', authTeacherReg.teacher)
router.post('/forget', authForget.forget)
router.post('/schedule', authSchedule.schedule)
router.post('/admin', authAdmin.admin)
router.post('/teacherEdit', authTeacherEdit.teacherEdit)
router.post('/archiveTeacher', authArchive.archiveTeacher);
router.post('/studentEdit', authStudentEdit.studentEdit)
router.post('/archiveStudent', authArchiveStudent.archiveStudent);
router.post('/adminEdit', authAdminEdit.adminEdit)
router.post('/archiveAdmin', authAdminArchive.archiveAdmin)
router.post('/Editschedule', authScheduleEdit.scheduleEdit)
router.post('/Archiveschedule', authScheduleArchive.archiveSchedule)
router.post('/UnarchiveAdmin', authUnAdminArchive.UnarchiveAdmin)
router.post('/UnarchiveSchedule', authUnScheduleArchive.UnarchiveSchedule)
router.post('/UnarchiveStudent', authUnArchiveStudent.UnarchiveStudent);
router.post('/UnarchiveTeacher', authUnArchive.UnarchiveTeacher);
module.exports = router;